# Generated by Django 4.2.4 on 2023-08-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
