# Generated by Django 4.2.4 on 2023-08-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(max_length=100)),
                ('updated_at', models.DateTimeField(max_length=501)),
            ],
        ),
        migrations.CreateModel(
            name='Recent_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('images', models.ImageField(upload_to='media/product')),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('is_stock', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ball.category')),
            ],
        ),
    ]
