# Generated by Django 3.2.20 on 2023-08-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ball', '0002_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
