# Generated by Django 4.2.4 on 2023-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloon', '0006_ourteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
