# Generated by Django 4.2.4 on 2023-09-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='card',
            new_name='cart',
        ),
    ]
